<Project>
  <PropertyGroup Label=".Net version" Condition=" '$(TargetFramework)' == 'net8.0' ">
    <NetCoreVersion>8.0.22</NetCoreVersion>
  </PropertyGroup>
  <PropertyGroup Label=".Net version" Condition=" '$(TargetFramework)' == 'net9.0' ">
    <NetCoreVersion>9.0.11</NetCoreVersion>
  </PropertyGroup>
  <PropertyGroup Label=".Net version" Condition=" '$(TargetFramework)' == 'net10.0' ">
	<NetCoreVersion>10.0.1</NetCoreVersion>
  </PropertyGroup>
  <ItemGroup Label="General Dependencies">
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="$(NetCoreVersion)" />
  </ItemGroup>
  <ItemGroup Label="Sample Dependencies">
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="$(NetCoreVersion)" />
  </ItemGroup>
  <ItemGroup Label="Testing Dependencies">
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(NetCoreVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="FluentAssertions" Version="[7.2.0]" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
  <ItemGroup Label="Github Dependencies">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>