name: Acheve.TestHost Continous Integration
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.417
            5.0.101
            6.0.300
            7.0.302

      - name: Build
        run: dotnet build -c $BUILD_CONFIG

      - name: Test
        run: dotnet test -c $BUILD_CONFIG --no-build